# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phonations
email: contact@phonations.com
description: > # this means to ignore newlines until "baseurl:"
  Efficient, user-friendly, powerful, the rythmo band tradition brought
  into the digital universe, offering the best of both worlds.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: phonations
github_username:  phonations

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag

# Translation
t:
  en:
    url: "/"
    how: "See how it works"
    founder: "Founder"
    artistic-director: "Artistic director"
    key-partner: "Key partner"
    developer: "Developer"
    name: "Name"
    name-placeholder: "Your name"
    email: "Email"
    email-placeholder: "Email"
    message: "Message"
    message-placeholder: "Your message"
    address: "Where to meet"
    contact: "New business"
    employement: "Employement"
    send: "Send"
  fr:
    url: "/fr"
    how: "Comment ça marche"
    founder: "Fondateur"
    artistic-director: "Directeur artistique"
    key-partner: "Partenaire industriel"
    developer: "Développeur"
    name: "Nom"
    name-placeholder: "Votre nom"
    email: "Email"
    email-placeholder: "Email"
    message: "Message"
    message-placeholder: "Votre message"
    address: "Adresse"
    contact: "Contact"
    employement: "Emploi"
    send: "Envoyer"

