# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phonations
email: contact@phonations.com
description: > # this means to ignore newlines until "baseurl:"
  Efficient, user-friendly, powerful, the rythmo band tradition brought
  into the digital universe, offering the best of both worlds.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: phonations
github_username:  phonations

# Build settings
markdown: kramdown
